language: java
jdk:
- oraclejdk8

addons:
    sonarcloud:
        organization: "justin-to-github"
        token:
                secure: "e647c94d8e42c99ea223ed0e6f2c875d2e9287ac"
script:
    - ant build
    - sonar-scanner
